### ISSUE TITLE
is the reference to table USER_DEVICE correct?

### ISSUE THREAD

**Issue by HandCarvedWoodenSpoon** [IBM-Security/isam-support#1]
Are you sure the DEVICE_ID index and table USER_DEVICE is valid? That table does not exist in my HVDB.

row 26 of the spreadsheet:
db2   create index DEVICE_ID on USER_DEVICE(DEVICE_ID) COLLECT DETAILED STATISTICS;

**Comment by HandCarvedWoodenSpoon** [comment]
Looks like table USER_DEVICE is for TFIM 6.2.2.16

**Comment by nick-lloyd** [comment]
Hi,

Thanks for the comment.
The spreadsheet covers more than a few versions.  I will double check and update where necessary.

Nick

**Comment by nick-lloyd** [comment]
FYI that was an older table for TFIM.
